//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int invoiceID { get; set; }
        public string parcelID { get; set; }
        public string customerID { get; set; }
        public double cost { get; set; }
        public System.DateTime outputTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Parcel Parcel { get; set; }
    }
}
