//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parcel()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public string parcelID { get; set; }
        public string parcelName { get; set; }
        public Nullable<double> parcelValue { get; set; }
        public string parcelStatus { get; set; }
        public double parcelMass { get; set; }
        public string parcelSize { get; set; }
        public string customerID { get; set; }
        public string type { get; set; }
        public System.DateTime createTime { get; set; }
        public int shippingFeeID { get; set; }
        public string batchID { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ShippingFee ShippingFee { get; set; }
    }
}
