//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseManager
    {
        public string warehouseManagerID { get; set; }
        public string warehouseManagerName { get; set; }
        public string warehouseManagerLocation { get; set; }
        public string warehouseManagerPhoneNumber { get; set; }
        public string warehouseID { get; set; }
        public int numberOfEmployee { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
    }
}
