//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseStaff
    {
        public string warehouseStaffID { get; set; }
        public string warehouseStaffName { get; set; }
        public string warehouseStaffLocation { get; set; }
        public string warehouseStaffPhoneNumber { get; set; }
        public string warehouseID { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
    }
}
